#ifndef BEDROCK_BUFIO_COMMON_H
#define BEDROCK_BUFIO_COMMON_H

#include <bedrock/io/io.h>

BR_EXTERN_C_BEGIN

enum {
  BR_BUFIO_DEFAULT_BUFFER_SIZE = 4096u,
  BR_BUFIO_MIN_BUFFER_SIZE = 16u,
  BR_BUFIO_DEFAULT_MAX_CONSECUTIVE_EMPTY_READS = 128u,
  BR_BUFIO_DEFAULT_MAX_CONSECUTIVE_EMPTY_WRITES = 128u
};

BR_EXTERN_C_END

#endif
